apiVersion: v2
name: taiko-client-prover
description: A Helm chart for Kubernetes
type: application
version: 0.1.2
maintainers:
  - name: d1onys1us

dependencies:
  - name: taiko-client
    version: "0.1.3"
    repository: "file://../taiko-client"
