apiVersion: v1
kind: Service
metadata:
  name: {{ include "taiko-geth.fullname" . }}
  labels:
    {{- include "taiko-geth.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "taiko-geth.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.global.ports.wsPort }}
      targetPort: ws-rpc
      protocol: TCP
      name: ws-rpc
    - port: {{ .Values.global.ports.httpPort }}
      targetPort: http-rpc
      protocol: TCP
      name: http-rpc
    - port: {{ .Values.global.ports.p2pPort }}
      targetPort: p2p-tcp
      protocol: TCP
      name: p2p-tcp
    - port: {{ .Values.global.ports.p2pPort }}
      targetPort: p2p-udp
      protocol: UDP
      name: p2p-udp
    - port: {{ .Values.global.ports.authPort }}
      targetPort: auth-rpc
      protocol: TCP
      name: auth-rpc
    - port: {{ .Values.global.ports.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
