global:
  network: hekla

taiko-client:
  global:
    network: "{{ .Values.global.network }}"
    mode: driver
    resources:
      requests:
        cpu: 1000m
        memory: 500Mi
      limits:
        cpu: 1000m
        memory: 500Mi
    replicaCount: 1
    l1Endpoints:
      l1Http: "http://ethereum-node-execution:8545"
      l1Ws: "ws://ethereum-node-execution:8546"
      l1Beacon: "http://ethereum-node-beacon:5052"

taiko-geth:
  global:
    network: "{{ .Values.global.network }}"
