apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taiko-client.fullname" . }}-jwt
type: Opaque
data:
  default: {{ .Values.global.secret.jwt | b64enc }}
{{- if eq .Values.global.mode "proposer" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taiko-client.fullname" . }}-proposer-private-key
type: Opaque
data:
  default: {{.Values.global.secret.proposerPrivateKey | b64enc}}
{{- end }}
{{- if eq .Values.global.mode "prover" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taiko-client.fullname" . }}-prover-private-key
type: Opaque
data:
  default: {{.Values.global.secret.proverPrivateKey | b64enc}}
{{- end }}
