taiko-client:
  global:
    network: hekla
    mode: guardian
    # Change these to the values of the svc in your namespace
    l1Endpoints:
      l1Http: "http://ethereum-node-holesky-execution:8545"
      l1Ws: "ws://ethereum-node-holesky-execution:8545"
      l1Beacon: "http://ethereum-node-holesky-beacon:5052"
    l2Endpoints:
      l2Http: "http://taiko-node-taiko-geth:8545"
      l2Ws: "ws://taiko-node-taiko-geth:8546"
      l2Auth: "http://taiko-node-taiko-geth:8551"
    # WARN: do not commit these values, using external secrets is recommended
    secret:
      guardianPrivateKey: ""
    resources:
      requests:
        cpu: 1000m
        memory: 500Mi
      limits:
        cpu: 1000m
        memory: 500Mi
    replicaCount: 1
  hekla:
    guardian:
      capacity: 1024
      healthCheckServer: https://guardian-prover-health-check.hekla.taiko.xyz
      contractAddresses:
        guardianProverMinority: "0x31d4d27da5c299d4b6CE19c869B8891C0002795d"
        guardianProverMajority: "0x92F195a8702da2104aE8E3E10779176E7C35d6BC"
      txGasLimit: "3000000"
      taikoGethVersion: v1.5.0
      l1NodeInfo: "lighthouse:latest/go-ethereum:stable"
  mainnet:
    guardian:
      capacity: 1024
      healthCheckServer: https://guardians-api.mainnet.taiko.xyz
      contractAddresses:
        guardianProverMinority: "0x579A8d63a2Db646284CBFE31FE5082c9989E985c"
        guardianProverMajority: "0xE3D777143Ea25A6E031d1e921F396750885f43aC"
      txGasLimit: "3000000"
      taikoGethVersion: v1.5.0
      l1NodeInfo: "lighthouse:latest/go-ethereum:stable"
