apiVersion: v2
name: taiko-client-proposer
description: A Helm chart for Kubernetes
type: application
version: 0.1.1
maintainers:
  - name: d1onys1us

dependencies:
  - name: taiko-client
    version: "0.1.2"
    repository: "file://../taiko-client"
